using GHLearning.EasyDomainDrivenDesign.Domain.SeedWork;

namespace GHLearning.EasyDomainDrivenDesign.Domain.Announcement;

public interface IAnnouncementDomainEventDispatcher : IDomainEventDispatcher;